# legal_preprocessing/legal_text_cleaner.py

from __future__ import annotations

import re
import unicodedata
from dataclasses import dataclass, field
from typing import List, Tuple


# ============================================================================
# REPORT
# ============================================================================

@dataclass
class CleaningReport:
    """
    Audit report for legal text preprocessing.

    The cleaner is deliberately conservative:
        - removes PDF/layout artifacts
        - normalizes whitespace
        - repairs obvious PDF hyphenation
        - detects suspicious joined words

    It does NOT:
        - spell-correct
        - infer missing words
        - split arbitrary words
        - rewrite legal language
        - modify citations
        - modify dates
        - use an LLM
    """

    original_characters: int = 0
    cleaned_characters: int = 0

    # PDF artifacts
    page_markers_removed: int = 0
    standalone_page_numbers_removed: int = 0

    # Text normalization
    unicode_normalizations: int = 0
    soft_hyphens_removed: int = 0
    ligatures_normalized: int = 0

    # Line handling
    hyphenated_line_breaks_repaired: int = 0
    line_breaks_normalized: int = 0

    # Suspicious text
    suspicious_joined_words: int = 0

    warnings: List[str] = field(default_factory=list)

    # Candidate joined words for later review
    suspicious_words: List[dict] = field(default_factory=list)

    @property
    def characters_removed(self) -> int:
        return max(
            0,
            self.original_characters - self.cleaned_characters
        )

    def to_dict(self) -> dict:
        return {
            "original_characters": self.original_characters,
            "cleaned_characters": self.cleaned_characters,
            "characters_removed": self.characters_removed,

            "page_markers_removed": self.page_markers_removed,
            "standalone_page_numbers_removed": (
                self.standalone_page_numbers_removed
            ),

            "unicode_normalizations": (
                self.unicode_normalizations
            ),
            "soft_hyphens_removed": (
                self.soft_hyphens_removed
            ),
            "ligatures_normalized": (
                self.ligatures_normalized
            ),

            "hyphenated_line_breaks_repaired": (
                self.hyphenated_line_breaks_repaired
            ),
            "line_breaks_normalized": (
                self.line_breaks_normalized
            ),

            "suspicious_joined_words": (
                self.suspicious_joined_words
            ),

            "warnings": self.warnings,

            "suspicious_words": self.suspicious_words,
        }


# ============================================================================
# CLEANER
# ============================================================================

class LegalTextCleaner:
    """
    Conservative PDF-extracted legal text cleaner.

    V2 philosophy:

        PDF extraction artifacts
                 |
                 v
        deterministic cleanup
                 |
                 v
        clean legal text

    No semantic guessing is performed.
    """

    # ------------------------------------------------------------------------
    # PDF page markers observed in the supplied judgment.
    #
    # Examples:
    #   3 | Pag e
    #   15 | Pag e
    #   51 | Page
    # ------------------------------------------------------------------------

    PAGE_MARKER_PATTERNS = [
        re.compile(
            r"\b\d+\s*\|\s*Pag\s*e\b",
            flags=re.IGNORECASE,
        ),
        re.compile(
            r"\b\d+\s*\|\s*Page\b",
            flags=re.IGNORECASE,
        ),
    ]

    # ------------------------------------------------------------------------
    # Standalone page number.
    #
    # Only removed when the COMPLETE line is a number.
    # ------------------------------------------------------------------------

    STANDALONE_PAGE_NUMBER = re.compile(
        r"^\s*\d+\s*$"
    )

    # ------------------------------------------------------------------------
    # Soft hyphen.
    # ------------------------------------------------------------------------

    SOFT_HYPHEN = "\u00ad"

    # ------------------------------------------------------------------------
    # Common Unicode ligatures generated by PDF extraction.
    # ------------------------------------------------------------------------

    LIGATURES = {
        "ﬀ": "ff",
        "ﬁ": "fi",
        "ﬂ": "fl",
        "ﬃ": "ffi",
        "ﬄ": "ffl",
        "ﬅ": "ft",
        "ﬆ": "st",
    }

    # ------------------------------------------------------------------------
    # Hyphen followed by a line break.
    #
    # Example:
    #
    #   amend-
    #   ment
    #
    # becomes:
    #
    #   amendment
    #
    # This is still deterministic PDF cleanup.
    # ------------------------------------------------------------------------

    HYPHENATED_LINE_BREAK = re.compile(
        r"(?<=\w)-[ \t]*\n[ \t]*(?=\w)"
    )

    # ------------------------------------------------------------------------
    # Spaces around line breaks.
    # ------------------------------------------------------------------------

    SPACES_BEFORE_NEWLINE = re.compile(
        r"[ \t]+\n"
    )

    SPACES_AFTER_NEWLINE = re.compile(
        r"\n[ \t]+"
    )

    # ------------------------------------------------------------------------
    # Multiple spaces.
    # ------------------------------------------------------------------------

    MULTIPLE_SPACES = re.compile(
        r"[ \t]+"
    )

    # ------------------------------------------------------------------------
    # Excessive blank lines.
    # ------------------------------------------------------------------------

    EXCESSIVE_BLANK_LINES = re.compile(
        r"\n[ \t]*\n(?:[ \t]*\n)+"
    )

    # ------------------------------------------------------------------------
    # Candidate suspicious joined word.
    #
    # IMPORTANT:
    #
    # This regex DOES NOT modify anything.
    #
    # It only finds long alphabetic tokens that may contain multiple words.
    #
    # Example:
    #
    #   certainamendments
    #   contributionmade
    #   pensionable
    #
    # These are reported for later analysis.
    # ------------------------------------------------------------------------

    LONG_ALPHA_TOKEN = re.compile(
        r"\b[A-Za-z]{12,}\b"
    )

    # ------------------------------------------------------------------------
    # Known safe-looking concatenation patterns.
    #
    # These are ONLY detectors, not replacements.
    # ------------------------------------------------------------------------

    COMMON_JOINED_WORD_HINTS = (
        "the",
        "and",
        "of",
        "to",
        "in",
        "on",
        "for",
        "from",
        "with",
        "by",
        "as",
        "is",
        "was",
        "were",
        "has",
        "have",
        "had",
        "that",
        "this",
        "such",
        "said",
        "under",
        "shall",
        "may",
        "would",
        "could",
        "should",
        "scheme",
        "act",
        "section",
        "paragraph",
        "employee",
        "employees",
        "contribution",
        "government",
        "pension",
        "fund",
    )

    def __init__(
        self,
        remove_page_markers: bool = True,
        remove_standalone_page_numbers: bool = True,
        normalize_unicode: bool = True,
        remove_soft_hyphens: bool = True,
        normalize_ligatures: bool = True,
        repair_hyphenated_line_breaks: bool = True,
        normalize_line_breaks: bool = True,
    ):
        self.remove_page_markers = remove_page_markers
        self.remove_standalone_page_numbers = (
            remove_standalone_page_numbers
        )
        self.normalize_unicode = normalize_unicode
        self.remove_soft_hyphens = remove_soft_hyphens
        self.normalize_ligatures = normalize_ligatures
        self.repair_hyphenated_line_breaks = (
            repair_hyphenated_line_breaks
        )
        self.normalize_line_breaks = normalize_line_breaks

    # ========================================================================
    # PUBLIC API
    # ========================================================================

    def clean(
        self,
        text: str,
    ) -> Tuple[str, CleaningReport]:

        if not isinstance(text, str):
            raise TypeError(
                f"text must be str, got {type(text).__name__}"
            )

        report = CleaningReport(
            original_characters=len(text)
        )

        cleaned = text

        # --------------------------------------------------------------
        # 1. Normalize line endings
        # --------------------------------------------------------------

        cleaned = cleaned.replace("\r\n", "\n")
        cleaned = cleaned.replace("\r", "\n")

        # --------------------------------------------------------------
        # 2. Unicode normalization
        # --------------------------------------------------------------

        if self.normalize_unicode:

            normalized = unicodedata.normalize(
                "NFKC",
                cleaned,
            )

            if normalized != cleaned:
                report.unicode_normalizations = 1

            cleaned = normalized

        # --------------------------------------------------------------
        # 3. Soft hyphens
        # --------------------------------------------------------------

        if self.remove_soft_hyphens:

            count = cleaned.count(
                self.SOFT_HYPHEN
            )

            if count:
                cleaned = cleaned.replace(
                    self.SOFT_HYPHEN,
                    "",
                )

            report.soft_hyphens_removed = count

        # --------------------------------------------------------------
        # 4. Ligatures
        # --------------------------------------------------------------

        if self.normalize_ligatures:

            for old, new in self.LIGATURES.items():

                count = cleaned.count(old)

                if count:
                    cleaned = cleaned.replace(
                        old,
                        new,
                    )

                    report.ligatures_normalized += count

        # --------------------------------------------------------------
        # 5. Page markers
        # --------------------------------------------------------------

        if self.remove_page_markers:

            cleaned, count = (
                self._remove_page_markers(cleaned)
            )

            report.page_markers_removed = count

        # --------------------------------------------------------------
        # 6. Standalone page numbers
        # --------------------------------------------------------------

        if self.remove_standalone_page_numbers:

            cleaned, count = (
                self._remove_standalone_page_numbers(
                    cleaned
                )
            )

            report.standalone_page_numbers_removed = count

        # --------------------------------------------------------------
        # 7. Hyphenated line breaks
        #
        # This is the ONLY automatic word reconstruction.
        # --------------------------------------------------------------

        if self.repair_hyphenated_line_breaks:

            cleaned, count = (
                self._repair_hyphenated_line_breaks(
                    cleaned
                )
            )

            report.hyphenated_line_breaks_repaired = count

        # --------------------------------------------------------------
        # 8. Normalize line whitespace
        #
        # IMPORTANT:
        #
        # We DO NOT remove arbitrary newlines.
        # Paragraph boundaries remain intact.
        # --------------------------------------------------------------

        if self.normalize_line_breaks:

            cleaned, count = (
                self._normalize_line_breaks(
                    cleaned
                )
            )

            report.line_breaks_normalized = count

        # --------------------------------------------------------------
        # 9. Detect suspicious joined words.
        #
        # NO MODIFICATION.
        # --------------------------------------------------------------

        suspicious = (
            self.detect_suspicious_joined_words(
                cleaned
            )
        )

        report.suspicious_words = suspicious
        report.suspicious_joined_words = len(
            suspicious
        )

        # --------------------------------------------------------------
        # 10. Final cleanup
        # --------------------------------------------------------------

        cleaned = cleaned.strip()

        report.cleaned_characters = len(cleaned)

        return cleaned, report

    # ========================================================================
    # PAGE MARKERS
    # ========================================================================

    def _remove_page_markers(
        self,
        text: str,
    ) -> Tuple[str, int]:

        total_count = 0

        for pattern in self.PAGE_MARKER_PATTERNS:

            text, count = pattern.subn(
                " ",
                text,
            )

            total_count += count

        return text, total_count

    # ========================================================================
    # PAGE NUMBERS
    # ========================================================================

    def _remove_standalone_page_numbers(
        self,
        text: str,
    ) -> Tuple[str, int]:

        lines = text.split("\n")

        output = []
        removed = 0

        for line in lines:

            if self.STANDALONE_PAGE_NUMBER.match(
                line
            ):
                removed += 1
                continue

            output.append(line)

        return "\n".join(output), removed

    # ========================================================================
    # HYPHENATED LINE BREAKS
    # ========================================================================

    def _repair_hyphenated_line_breaks(
        self,
        text: str,
    ) -> Tuple[str, int]:

        matches = list(
            self.HYPHENATED_LINE_BREAK.finditer(
                text
            )
        )

        if not matches:
            return text, 0

        repaired = self.HYPHENATED_LINE_BREAK.sub(
            "",
            text,
        )

        return repaired, len(matches)

    # ========================================================================
    # LINE BREAK NORMALIZATION
    # ========================================================================

    def _normalize_line_breaks(
        self,
        text: str,
    ) -> Tuple[str, int]:

        original = text

        # Remove whitespace at the end of lines.
        text = self.SPACES_BEFORE_NEWLINE.sub(
            "\n",
            text,
        )

        # Remove indentation introduced by PDF extraction.
        text = self.SPACES_AFTER_NEWLINE.sub(
            "\n",
            text,
        )

        # Multiple spaces -> one.
        text = self.MULTIPLE_SPACES.sub(
            " ",
            text,
        )

        # More than one blank line -> one blank line.
        text = self.EXCESSIVE_BLANK_LINES.sub(
            "\n\n",
            text,
        )

        changed = int(text != original)

        return text, changed

    def detect_suspicious_joined_words(
        self,
        text: str,
    ) -> list[dict]:
        """
        Detect potentially joined words introduced by PDF/text extraction.

        IMPORTANT:
        - This method is diagnostic only.
        - It NEVER modifies the supplied text.
        - It should produce candidates for manual review.
        - Purely numeric tokens are ignored.
        - Alphanumeric legal references such as 'post2014' are handled
        separately from ordinary alphabetic joined words.

        Examples of candidates:
            employeremployee -> employer + employee
            timelimit        -> time + limit
            onethird         -> one + third
            post2014         -> post + 2014

        Examples that must NOT be flagged:
            5
            2014
            (5)
            Section 5
            Rs.5,75,918.88
            1.9.2014
        """
        print(
            "[DEBUG] NEW detect_suspicious_joined_words() CALLED",
            flush=True,
        )

        import re
        from collections import Counter

        # ---------------------------------------------------------
        # Configuration
        # ---------------------------------------------------------

        MIN_ALPHA_TOKEN_LENGTH = 10
        MIN_COMPONENT_LENGTH = 3
        MIN_COMPONENT_FREQUENCY = 2

        # ---------------------------------------------------------
        # Tokenize
        #
        # Keep alphanumeric tokens because we specifically want
        # to detect things such as:
        #
        #     post2014
        #     section12
        #
        # But punctuation is excluded.
        # ---------------------------------------------------------

        tokens = re.findall(
            r"\b[A-Za-z][A-Za-z0-9]*\b",
            text,
        )

        if not tokens:
            return []

        normalized_tokens = [
            token.lower()
            for token in tokens
        ]

        vocabulary = Counter(normalized_tokens)

        candidates = []

        # ---------------------------------------------------------
        # Helper: check whether a token is a normal alphabetic word
        # ---------------------------------------------------------

        def is_alpha_word(token: str) -> bool:
            return token.isalpha()

        # ---------------------------------------------------------
        # Helper: check whether a token contains digits
        # ---------------------------------------------------------

        def is_alphanumeric(token: str) -> bool:
            return any(ch.isdigit() for ch in token) and any(
                ch.isalpha() for ch in token
            )

        # ---------------------------------------------------------
        # Helper: add candidate while avoiding duplicates
        # ---------------------------------------------------------

        seen = set()

        def add_candidate(
            word: str,
            suggested_split: str,
            left_frequency: int,
            right_frequency: int,
            evidence_score: int,
            candidate_type: str,
        ):
            key = (
                word.lower(),
                suggested_split.lower(),
            )

            if key in seen:
                return

            seen.add(key)

            candidates.append(
                {
                    "word": word,
                    "suggested_split": suggested_split,
                    "left_frequency": left_frequency,
                    "right_frequency": right_frequency,
                    "evidence_score": evidence_score,
                    "candidate_type": candidate_type,
                }
            )

        # ---------------------------------------------------------
        # Process tokens
        # ---------------------------------------------------------

        for original_token, token_lower in zip(
            tokens,
            normalized_tokens,
        ):

            # =====================================================
            # 1. PURE NUMERIC TOKENS
            #
            # Never flag:
            #
            #     5
            #     2014
            #     6500
            #     15000
            #
            # This fixes the current false-positive problem.
            # =====================================================

            if token_lower.isdigit():
                continue

            # =====================================================
            # 2. ALPHANUMERIC TOKENS
            #
            # Handle legal/PDF extraction candidates such as:
            #
            #     post2014
            #     section12
            #     paragraph11
            #
            # We deliberately do NOT attempt arbitrary splitting.
            # Only a known alphabetic prefix followed by a year or
            # numeric suffix is considered.
            # =====================================================

            if is_alphanumeric(token_lower):

                # -------------------------------------------------
                # Pattern A:
                #
                #     post2014
                #     pre2014
                #
                # alphabetic prefix + four digit number
                # -------------------------------------------------

                match = re.fullmatch(
                    r"([A-Za-z]{3,})(\d{4})",
                    original_token,
                )

                if match:

                    alpha_part = match.group(1).lower()
                    numeric_part = match.group(2)

                    alpha_frequency = vocabulary.get(
                        alpha_part,
                        0,
                    )

                    if alpha_frequency >= MIN_COMPONENT_FREQUENCY:

                        add_candidate(
                            word=original_token,
                            suggested_split=(
                                f"{alpha_part} + {numeric_part}"
                            ),
                            left_frequency=alpha_frequency,
                            right_frequency=0,
                            evidence_score=alpha_frequency,
                            candidate_type="alphanumeric",
                        )

                    # We have handled this token.
                    continue

                # -------------------------------------------------
                # Other alphanumeric strings are ignored.
                #
                # This avoids false positives from:
                #
                #     SLP3289
                #     GSR609
                #     6A
                #     11(3)
                # etc.
                # -------------------------------------------------

                continue

            # =====================================================
            # 3. ORDINARY ALPHABETIC TOKENS
            # =====================================================

            if not is_alpha_word(token_lower):
                continue

            # Ignore short words.
            if len(token_lower) < MIN_ALPHA_TOKEN_LENGTH:
                continue

            # -----------------------------------------------------
            # Try every possible split.
            #
            # Example:
            #
            # employeremployee
            #
            # employer | employee
            # employe | remployee
            # ...
            #
            # Only accept a split when BOTH sides independently
            # occur in the document vocabulary.
            # -----------------------------------------------------

            for split_position in range(
                MIN_COMPONENT_LENGTH,
                len(token_lower) - MIN_COMPONENT_LENGTH + 1,
            ):

                left = token_lower[:split_position]
                right = token_lower[split_position:]

                # Both components must be alphabetic.
                if not left.isalpha() or not right.isalpha():
                    continue

                # Both components must independently occur in the
                # document.
                left_frequency = vocabulary.get(left, 0)
                right_frequency = vocabulary.get(right, 0)

                if left_frequency < MIN_COMPONENT_FREQUENCY:
                    continue

                if right_frequency < MIN_COMPONENT_FREQUENCY:
                    continue

                # -------------------------------------------------
                # Evidence score
                #
                # Higher frequency + longer components means
                # stronger evidence.
                # -------------------------------------------------

                evidence_score = (
                    left_frequency
                    + right_frequency
                    + len(left)
                    + len(right)
                )

                add_candidate(
                    word=original_token,
                    suggested_split=(
                        f"{left} + {right}"
                    ),
                    left_frequency=left_frequency,
                    right_frequency=right_frequency,
                    evidence_score=evidence_score,
                    candidate_type="alphabetic",
                )

        # ---------------------------------------------------------
        # Keep only the strongest candidate for each suspicious
        # word.
        #
        # A word can technically have multiple possible splits.
        # For example:
        #
        #     somethingelse
        #
        # We want the most convincing split rather than flooding
        # the report with every possible combination.
        # ---------------------------------------------------------

        best_candidates = {}

        for candidate in candidates:

            word_key = candidate["word"].lower()

            existing = best_candidates.get(word_key)

            if existing is None:
                best_candidates[word_key] = candidate
                continue

            if candidate["evidence_score"] > existing["evidence_score"]:
                best_candidates[word_key] = candidate

        candidates = list(best_candidates.values())

        # ---------------------------------------------------------
        # Sort:
        #
        # 1. strongest evidence first
        # 2. longer suspicious words first
        # 3. alphabetical order for deterministic output
        # ---------------------------------------------------------

        candidates.sort(
            key=lambda item: (
                -item["evidence_score"],
                -len(item["word"]),
                item["word"].lower(),
            )
        )
        
        print(
            "[DEBUG] DETECTOR RETURN:",
            candidates,
            flush=True,
        )

        return candidates
    # ========================================================================
    # JOINED WORD HEURISTIC
    # ========================================================================

    def _looks_like_joined_word(
        self,
        word: str,
    ) -> bool:

        word_lower = word.lower()

        # --------------------------------------------------------------
        # Very long tokens are suspicious.
        # --------------------------------------------------------------

        if len(word) >= 22:
            return True

        # --------------------------------------------------------------
        # Detect common legal words embedded inside a larger token.
        #
        # Example:
        #
        #   contributionmade
        #
        # contains "contribution"
        # and "made" is a likely continuation.
        # --------------------------------------------------------------

        for hint in self.COMMON_JOINED_WORD_HINTS:

            if (
                word_lower.startswith(hint)
                and len(word_lower) > len(hint) + 3
            ):
                return True

            if (
                word_lower.endswith(hint)
                and len(word_lower) > len(hint) + 3
            ):
                return True

        return False


# ============================================================================
# CONVENIENCE FUNCTION
# ============================================================================

def clean_legal_text(
    text: str,
    **kwargs,
) -> Tuple[str, CleaningReport]:

    cleaner = LegalTextCleaner(
        **kwargs
    )

    return cleaner.clean(text)