"""
Canonical legal document builder for the OpenNyAI-based RAG pipeline.

Pipeline
--------
OpenNyAI outputs
    |
    +-- Rhetorical Role Classification (RRC)
    |
    +-- Named Entity Recognition (NER)
    |
    +-- Extractive Summarizer
    |
    v
LegalDocument
    |
    v
rag.ingestion.chunker
    |
    v
LegalChunk


Important design principle
--------------------------
The cleaned legal judgment remains the authoritative source text.

NER and summarizer outputs are enrichment/context layers.

RRC provides the legal rhetorical structure.

This module does NOT:
    - generate embeddings
    - communicate with Qdrant
    - call the LLM
    - perform retrieval
    - perform semantic chunking
"""

from __future__ import annotations

from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional
import hashlib
import json


# ============================================================================
# Configuration
# ============================================================================

DOCUMENT_SCHEMA_VERSION = "2.0"

DEFAULT_LANGUAGE = "en"
DEFAULT_SOURCE_TYPE = "legal_judgment"


# ============================================================================
# Data models
# ============================================================================

@dataclass
class LegalAnnotation:
    """
    One OpenNyAI rhetorical-role annotation.

    RRC annotations are treated as the fundamental legal structural units.
    """

    annotation_id: str

    text: str

    role: str

    char_start: int
    char_end: int

    annotation_index: int


@dataclass
class LegalEntity:
    """
    Normalized NER entity.

    Offsets are optional because different OpenNyAI NER output formats may
    provide or omit them.
    """

    entity_id: str

    text: str

    label: str

    char_start: Optional[int] = None
    char_end: Optional[int] = None
    
    normalized_name: str | None = None

    source: str = "opennyai_ner"


@dataclass
class LegalSummary:
    """
    Document-level summary generated by the OpenNyAI summarizer.

    These are NOT authoritative legal source text. They are contextual
    information used to enrich retrieval and generation.
    """

    preamble: Optional[str] = None
    facts: Optional[str] = None
    issue: Optional[str] = None
    arguments: Optional[str] = None
    analysis: Optional[str] = None
    decision: Optional[str] = None

    # Preserve any additional sections emitted by a future OpenNyAI
    # summarizer version.
    extra: Dict[str, str] = field(default_factory=dict)


@dataclass
class LegalDocument:
    """
    Canonical legal document representation.

    This is the contract between document_builder.py and chunker.py.
    """

    document_id: str

    source_file: Optional[str]

    source_type: str

    language: str

    text: str

    text_length: int

    annotations: List[LegalAnnotation]

    annotation_count: int

    entities: List[LegalEntity]

    entity_count: int

    summary: LegalSummary

    # Optional trusted document metadata.
    case_name: Optional[str] = None
    citation: Optional[str] = None
    court: Optional[str] = None
    judgment_date: Optional[str] = None

    schema_version: str = DOCUMENT_SCHEMA_VERSION


# ============================================================================
# Generic JSON helpers
# ============================================================================

def load_json(path: str | Path) -> Any:
    """
    Load UTF-8 JSON from disk.
    """

    path = Path(path)

    with path.open(
        "r",
        encoding="utf-8",
    ) as file:
        return json.load(file)


def save_json(
    data: Any,
    path: str | Path,
    *,
    indent: int = 2,
) -> None:
    """
    Save UTF-8 JSON.
    """

    path = Path(path)

    path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    with path.open(
        "w",
        encoding="utf-8",
    ) as file:
        json.dump(
            data,
            file,
            ensure_ascii=False,
            indent=indent,
        )


# ============================================================================
# Document ID
# ============================================================================

def generate_document_id(
    source_text: str,
) -> str:
    """
    Generate deterministic SHA-256 document ID.

    This is only used if OpenNyAI did not provide an ID.
    """

    return hashlib.sha256(
        source_text.encode("utf-8")
    ).hexdigest()


# ============================================================================
# RRC normalization
# ============================================================================

def get_role(
    annotation: Dict[str, Any],
) -> str:
    """
    Extract the rhetorical role from an OpenNyAI annotation.

    Expected form:

        "labels": ["ANALYSIS"]

    If no label exists, UNKNOWN is used.
    """

    labels = annotation.get("labels") or []

    if isinstance(labels, str):
        return labels.strip() or "UNKNOWN"

    if not labels:
        return "UNKNOWN"

    return str(
        labels[0]
    ).strip() or "UNKNOWN"


def get_annotation_text(
    annotation: Dict[str, Any],
    source_text: str,
) -> str:
    """
    Obtain annotation text.

    Prefer the text explicitly emitted by OpenNyAI.
    Otherwise reconstruct it from source offsets.
    """

    if annotation.get("text") is not None:
        return str(
            annotation["text"]
        )

    start = int(
        annotation["start"]
    )

    end = int(
        annotation["end"]
    )

    return source_text[start:end]


def normalize_annotations(
    source_text: str,
    annotations: Iterable[Dict[str, Any]],
) -> List[LegalAnnotation]:
    """
    Normalize raw OpenNyAI RRC annotations.

    Original character offsets are preserved.
    """

    normalized: List[LegalAnnotation] = []

    previous_end = -1

    for index, annotation in enumerate(annotations):

        if "start" not in annotation:
            raise ValueError(
                f"RRC annotation {index} is missing 'start'."
            )

        if "end" not in annotation:
            raise ValueError(
                f"RRC annotation {index} is missing 'end'."
            )

        start = int(
            annotation["start"]
        )

        end = int(
            annotation["end"]
        )

        if start < 0:
            raise ValueError(
                f"RRC annotation {index} has negative start."
            )

        if end < start:
            raise ValueError(
                f"RRC annotation {index} has end < start."
            )

        if end > len(source_text):
            raise ValueError(
                f"RRC annotation {index} ends at {end}, "
                f"but source length is {len(source_text)}."
            )

        if start < previous_end:
            raise ValueError(
                "Overlapping RRC annotations detected: "
                f"annotation {index} starts at {start}, "
                f"previous annotation ended at {previous_end}."
            )

        normalized.append(
            LegalAnnotation(
                annotation_id=str(
                    annotation.get(
                        "id",
                        f"annotation_{index}",
                    )
                ),
                text=get_annotation_text(
                    annotation,
                    source_text,
                ),
                role=get_role(
                    annotation
                ),
                char_start=start,
                char_end=end,
                annotation_index=index,
            )
        )

        previous_end = end

    return normalized


# ============================================================================
# NER normalization
# ============================================================================

def _get_first_value(
    data: Dict[str, Any],
    keys: Iterable[str],
) -> Any:
    """
    Return the first available value from a list of possible keys.
    """

    for key in keys:

        if key in data:
            return data[key]

    return None


def normalize_entities(
    data: Any,
    document_text: str | None = None,
) -> list[LegalEntity]:
    """
    Normalize OpenNyAI NER output.

    OpenNyAI NER structure:

        document
          -> annotations
              -> entities

    Entity offsets are absolute character offsets into the source document.

    If document_text is supplied, entities whose offsets fall outside the
    authoritative document are skipped rather than allowing invalid metadata
    into the LegalDocument.
    """
    if not data:
        return []

    entities: list[LegalEntity] = []

    documents = data if isinstance(data, list) else [data]

    document_length = len(document_text) if document_text is not None else None

    for document in documents:
        if not isinstance(document, dict):
            continue

        annotations = document.get("annotations", [])

        if not isinstance(annotations, list):
            continue

        for annotation in annotations:
            if not isinstance(annotation, dict):
                continue

            annotation_entities = annotation.get("entities", [])

            if not isinstance(annotation_entities, list):
                continue

            for entity in annotation_entities:
                if not isinstance(entity, dict):
                    continue

                entity_id = str(
                    entity.get("id")
                    or f"ner_{len(entities)}"
                )

                text = str(
                    entity.get("text")
                    or entity.get("normalized_name")
                    or ""
                ).strip()

                if not text:
                    continue

                normalized_name = str(
                    entity.get("normalized_name")
                    or text
                ).strip()

                labels = entity.get("labels", [])

                if isinstance(labels, str):
                    labels = [labels]

                if not labels:
                    labels = ["UNKNOWN"]

                start = entity.get("start")
                end = entity.get("end")

                try:
                    start = int(start) if start is not None else None
                except (TypeError, ValueError):
                    start = None

                try:
                    end = int(end) if end is not None else None
                except (TypeError, ValueError):
                    end = None

                # ---------------------------------------------------------
                # Validate offsets against the authoritative RRC text
                # ---------------------------------------------------------

                if document_length is not None:

                    if start is None or end is None:
                        print(
                            f"[NER] Skipping entity without valid offsets: "
                            f"{entity_id} ({text!r})"
                        )
                        continue

                    if start < 0 or end < start:
                        print(
                            f"[NER] Skipping invalid entity offsets: "
                            f"{entity_id} ({text!r}) "
                            f"[{start}, {end}]"
                        )
                        continue

                    if end > document_length:
                        print(
                            f"[NER] Skipping out-of-range entity: "
                            f"{entity_id} ({text!r}) "
                            f"[{start}, {end}] "
                            f"document_length={document_length}"
                        )
                        continue

                # ---------------------------------------------------------
                # Preserve one LegalEntity per label
                # ---------------------------------------------------------

                label = str(labels[0])

                entities.append(
                    LegalEntity(
                        entity_id=entity_id,
                        text=text,
                        label=label,
                        char_start=start,
                        char_end=end,
                        normalized_name=normalized_name,
                        source="opennyai_ner",
                    )
                )

    return entities
# ============================================================================
# Summary normalization
# ============================================================================

def normalize_summary(
    summary_data: Any,
) -> LegalSummary:
    """
    Normalize OpenNyAI summarizer output.

    Canonical sections:

        preamble
        facts
        issue
        arguments
        analysis
        decision

    Additional sections are preserved under `extra`.

    Missing sections remain None.
    """

    if not summary_data:
        return LegalSummary()

    # ---------------------------------------------------------------
    # Unwrap common list form:
    #
    # [
    #     {
    #         "summaries": {...}
    #     }
    # ]
    # ---------------------------------------------------------------

    if isinstance(
        summary_data,
        list,
    ):

        if not summary_data:
            return LegalSummary()

        if isinstance(
            summary_data[0],
            dict,
        ):

            summary_data = summary_data[0]

    # ---------------------------------------------------------------
    # Unwrap:
    #
    # {"summaries": {...}}
    # ---------------------------------------------------------------

    if isinstance(
        summary_data,
        dict
    ):

        if isinstance(
            summary_data.get(
                "summaries"
            ),
            dict,
        ):

            summary_data = summary_data[
                "summaries"
            ]

    if not isinstance(
        summary_data,
        dict,
    ):
        return LegalSummary()

    canonical: Dict[str, str] = {}

    extra: Dict[str, str] = {}

    aliases = {
        "preamble": "preamble",

        "facts": "facts",
        "fact": "facts",

        "issue": "issue",
        "issues": "issue",

        "arguments": "arguments",
        "argument": "arguments",

        "analysis": "analysis",

        "decision": "decision",

        "final_decision": "decision",
    }

    canonical_keys = set(
        aliases.values()
    )

    for raw_key, raw_value in (
        summary_data.items()
    ):

        if raw_value is None:
            continue

        if isinstance(
            raw_value,
            (dict, list),
        ):

            # We only want textual summary sections.
            continue

        text = str(
            raw_value
        ).strip()

        if not text:
            continue

        key = str(
            raw_key
        ).strip().lower()

        canonical_key = aliases.get(
            key
        )

        if canonical_key in canonical_keys:

            canonical[
                canonical_key
            ] = text

        else:

            extra[
                key
            ] = text

    return LegalSummary(
        preamble=canonical.get(
            "preamble"
        ),

        facts=canonical.get(
            "facts"
        ),

        issue=canonical.get(
            "issue"
        ),

        arguments=canonical.get(
            "arguments"
        ),

        analysis=canonical.get(
            "analysis"
        ),

        decision=canonical.get(
            "decision"
        ),

        extra=extra,
    )


# ============================================================================
# Metadata
# ============================================================================

def normalize_metadata(
    metadata: Optional[Dict[str, Any]],
) -> Dict[str, Optional[str]]:
    """
    Normalize trusted document metadata.

    The builder does not attempt to infer case names or citations from
    arbitrary text. Those can be added later by a dedicated metadata
    extractor if required.
    """

    metadata = metadata or {}

    def clean(
        value: Any,
    ) -> Optional[str]:

        if value is None:
            return None

        value = str(
            value
        ).strip()

        return value or None

    return {
        "case_name": clean(
            metadata.get(
                "case_name"
            )
        ),

        "citation": clean(
            metadata.get(
                "citation"
            )
        ),

        "court": clean(
            metadata.get(
                "court"
            )
        ),

        "judgment_date": clean(
            metadata.get(
                "judgment_date"
            )
        ),
    }


# ============================================================================
# Main builder
# ============================================================================

def build_document(
    rhetorical_document: Dict[str, Any],
    *,
    ner_data: Any = None,
    summary_data: Any = None,
    source_file: Optional[str] = None,
    metadata: Optional[Dict[str, Any]] = None,
    source_type: str = DEFAULT_SOURCE_TYPE,
    language: str = DEFAULT_LANGUAGE,
) -> LegalDocument:
    """
    Build one canonical LegalDocument.

    Parameters
    ----------
    rhetorical_document:
        One document from OpenNyAI rhetorical_roles output.

    ner_data:
        NER output corresponding to this document.

    summary_data:
        Summarizer output corresponding to this document.

    source_file:
        Source filename.

    metadata:
        Trusted metadata such as case_name, citation, court and date.
    """

    if not isinstance(
        rhetorical_document,
        dict,
    ):
        raise TypeError(
            "rhetorical_document must be a dictionary."
        )

    data = rhetorical_document.get(
        "data"
    )

    if not isinstance(
        data,
        dict,
    ):
        raise ValueError(
            "Rhetorical document is missing 'data'."
        )

    source_text = str(
        data.get(
            "text",
            ""
        )
    )

    if not source_text:
        raise ValueError(
            "Rhetorical document contains empty text."
        )

    raw_annotations = (
        rhetorical_document.get(
            "annotations",
            []
        )
    )

    if not isinstance(
        raw_annotations,
        list,
    ):
        raise ValueError(
            "'annotations' must be a list."
        )

    annotations = normalize_annotations(
        source_text=source_text,
        annotations=raw_annotations,
    )

    entities = normalize_entities(
        ner_data,
        document_text=source_text,
    )

    summary = normalize_summary(
        summary_data
    )

    document_id = (
        rhetorical_document.get(
            "id"
        )
    )

    if not document_id:

        document_id = generate_document_id(
            source_text
        )

    normalized_metadata = (
        normalize_metadata(
            metadata
        )
    )

    document = LegalDocument(
        document_id=str(
            document_id
        ),

        source_file=source_file,

        source_type=source_type,

        language=language,

        text=source_text,

        text_length=len(
            source_text
        ),

        annotations=annotations,

        annotation_count=len(
            annotations
        ),

        entities=entities,

        entity_count=len(
            entities
        ),

        summary=summary,

        case_name=normalized_metadata[
            "case_name"
        ],

        citation=normalized_metadata[
            "citation"
        ],

        court=normalized_metadata[
            "court"
        ],

        judgment_date=normalized_metadata[
            "judgment_date"
        ],
    )

    validate_document(
        document
    )

    return document


# ============================================================================
# File-level builder
# ============================================================================

def load_rhetorical_documents(
    path: str | Path,
) -> List[Dict[str, Any]]:
    """
    Load rhetorical_roles JSON.

    Expected top-level structure:

        [
            {...},
            {...}
        ]
    """

    data = load_json(
        path
    )

    if not isinstance(
        data,
        list,
    ):
        raise ValueError(
            f"Expected a list in {path}, "
            f"got {type(data).__name__}."
        )

    return data


def build_documents_from_file(
    rhetorical_roles_path: str | Path,
    *,
    ner_data: Any = None,
    summary_data: Any = None,
    metadata: Optional[Dict[str, Any]] = None,
    source_file: Optional[str] = None,
    source_type: str = DEFAULT_SOURCE_TYPE,
    language: str = DEFAULT_LANGUAGE,
) -> List[LegalDocument]:
    """
    Build canonical LegalDocument objects from OpenNyAI RRC output.

    Important:
        rhetorical_roles.json is an intermediate artifact.
        It must NOT become the legal source filename.

    source_file should normally be the original PDF filename.
    """

    rhetorical_roles_path = Path(
        rhetorical_roles_path
    )

    documents = load_rhetorical_documents(
        rhetorical_roles_path
    )

    # --------------------------------------------------------------
    # Determine source filename
    # --------------------------------------------------------------

    if source_file is None:
        source_file = rhetorical_roles_path.name

    metadata = dict(metadata or {})

    # --------------------------------------------------------------
    # If one RRC JSON represents one source PDF, derive a useful
    # fallback source filename from the directory name.
    #
    # Example:
    #
    # output/Sunil_Kumar_B/rhetorical_roles.json
    #
    # -> Sunil_Kumar_B.pdf
    # --------------------------------------------------------------

    if (
        source_file == rhetorical_roles_path.name
        and rhetorical_roles_path.parent.name
        not in {"", ".", "output", "processed"}
    ):
        folder_name = rhetorical_roles_path.parent.name

        source_file = (
            f"{folder_name}.pdf"
            if not folder_name.lower().endswith(".pdf")
            else folder_name
        )

    # --------------------------------------------------------------
    # Safe fallback metadata
    # --------------------------------------------------------------

    # We DO NOT invent a legal citation or court.
    #
    # We may however use the source document name as a searchable
    # case identity when no explicit case_name metadata exists.
    #
    # This is intentionally conservative.

    if not metadata.get("case_name"):
        stem = Path(source_file).stem

        cleaned = stem.replace(
            "_",
            " ",
        ).replace(
            "-",
            " ",
        ).strip()

        if cleaned:
            metadata["case_name"] = cleaned

    return [
        build_document(
            rhetorical_document=document,
            ner_data=ner_data,
            summary_data=summary_data,
            source_file=source_file,
            metadata=metadata,
            source_type=source_type,
            language=language,
        )
        for document in documents
    ]

# ============================================================================
# Serialization
# ============================================================================

def document_to_dict(
    document: LegalDocument,
) -> Dict[str, Any]:
    """
    Convert LegalDocument into JSON-compatible dictionary.
    """

    return asdict(
        document
    )


def save_document(
    document: LegalDocument,
    path: str | Path,
) -> None:
    """
    Save a LegalDocument to JSON.
    """

    save_json(
        document_to_dict(
            document
        ),
        path,
    )


# ============================================================================
# Validation
# ============================================================================

def validate_document(
    document: LegalDocument,
) -> None:
    """
    Validate the canonical document.

    RRC offsets must:
        - be non-negative
        - be ordered
        - not overlap
        - stay within source text
    """

    if not document.document_id:
        raise ValueError(
            "Document has no document_id."
        )

    if not document.text:
        raise ValueError(
            "Document has empty text."
        )

    if document.text_length != len(
        document.text
    ):
        raise ValueError(
            "Document text_length does not match "
            "actual text length."
        )

    if document.annotation_count != len(
        document.annotations
    ):
        raise ValueError(
            "Document annotation_count does not match "
            "actual annotation count."
        )

    if document.entity_count != len(
        document.entities
    ):
        raise ValueError(
            "Document entity_count does not match "
            "actual entity count."
        )

    previous_end = -1

    for annotation in document.annotations:

        if annotation.char_start < 0:
            raise ValueError(
                f"Negative annotation start: "
                f"{annotation.annotation_id}"
            )

        if annotation.char_end < annotation.char_start:
            raise ValueError(
                f"Invalid annotation offsets: "
                f"{annotation.annotation_id}"
            )

        if annotation.char_end > document.text_length:
            raise ValueError(
                f"Annotation extends beyond document: "
                f"{annotation.annotation_id}"
            )

        if annotation.char_start < previous_end:
            raise ValueError(
                f"Overlapping annotation: "
                f"{annotation.annotation_id}"
            )

        previous_end = annotation.char_end

    for entity in document.entities:

        if entity.char_start is None:
            continue

        if entity.char_start < 0:
            raise ValueError(
                f"Invalid entity start: "
                f"{entity.entity_id}"
            )

        if (
            entity.char_end is not None
            and entity.char_end < entity.char_start
        ):
            raise ValueError(
                f"Invalid entity offsets: "
                f"{entity.entity_id}"
            )

        if (
            entity.char_end is not None
            and entity.char_end > document.text_length
        ):
            raise ValueError(
                f"Entity extends beyond document: "
                f"{entity.entity_id}"
            )


# ============================================================================
# Statistics
# ============================================================================

def document_statistics(
    document: LegalDocument,
) -> Dict[str, Any]:
    """
    Generate useful M1 diagnostics.
    """

    role_counts: Dict[str, int] = {}

    for annotation in document.annotations:

        role = annotation.role

        role_counts[role] = (
            role_counts.get(
                role,
                0
            ) + 1
        )

    entity_counts: Dict[str, int] = {}

    for entity in document.entities:

        label = entity.label

        entity_counts[label] = (
            entity_counts.get(
                label,
                0
            ) + 1
        )

    return {
        "document_id": document.document_id,

        "source_file": document.source_file,

        "text_length": document.text_length,

        "annotation_count": document.annotation_count,

        "entity_count": document.entity_count,

        "rhetorical_roles": role_counts,

        "entity_types": entity_counts,

        "summary_sections": [
            key
            for key, value
            in asdict(
                document.summary
            ).items()
            if value
        ],

        "case_name": document.case_name,

        "citation": document.citation,

        "court": document.court,
    }


# ============================================================================
# Public API
# ============================================================================

__all__ = [
    "DOCUMENT_SCHEMA_VERSION",

    "LegalAnnotation",
    "LegalEntity",
    "LegalSummary",
    "LegalDocument",

    "load_json",
    "save_json",

    "generate_document_id",

    "get_role",
    "normalize_annotations",

    "normalize_entities",

    "normalize_summary",

    "normalize_metadata",

    "build_document",

    "load_rhetorical_documents",
    "build_documents_from_file",

    "document_to_dict",
    "save_document",

    "validate_document",

    "document_statistics",
]